// <auto-generated />
using CiPeWorldCup.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CiPeWorldCup.Infrastructure.Migrations
{
    [DbContext(typeof(CiPeWorldCupDbContext))]
    [Migration("20251125140823_20251125_FirstParticipantInjection_SeedParticipantSQL_Sprint.26.2_Migration")]
    partial class _20251125_FirstParticipantInjection_SeedParticipantSQL_Sprint262_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CiPeWorldCup.Core.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diana"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ethan"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fiona"
                        },
                        new
                        {
                            Id = 7,
                            Name = "George"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hannah"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Isaac"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Julia"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kevin"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Laura"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Michael"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Nina"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Oscar"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Paula"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Quentin"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Rachel"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Samuel"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Tina"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
